# .github/workflows/public-ecr.yml
name: Build and Push OpenVPN
on:
  push:

permissions:
      id-token: write
      contents: write    # This is required for actions/checkout@v1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v1
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNTID }}:role/github-openvpn
          role-session-name: samplerolesession
          aws-region: eu-west-1
      - name: Docker Login
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y9x3p3i6
      - name: Docker Build
        run: docker build -t roxprox-ratelimit .
      - name: Docker Tag 
        run: docker tag roxprox-ratelimit public.ecr.aws/y9x3p3i6/roxprox-ratelimit:latest
      - name: Docker Push
        run: docker push public.ecr.aws/y9x3p3i6/roxprox-ratelimit

